version: "3.7"

networks:
  app-network:
    driver: bridge

services: 
  app:
    container_name: app
    build:
      context: ./Docker/app
      dockerfile: Dockerfile
    image: api-pasinaon
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes: 
      - ./:/var/www
    networks: 
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports: 
        - 80:80
    volumes: 
        - ./:/var/www
        - ./Docker/nginx/conf:/etc/nginx/conf.d
    networks: 
        - app-network